version: '3.4'

services:
  preferencesmicroservice:
    image: ${DOCKER_REGISTRY-}preferencesmicroservice
    build:
      context: .
      dockerfile: PreferencesMicroService/Dockerfile
    ports:
        - "7175:7175"
    environment:
        - ASPNETCORE_URLS="https://+:7175;http://+:7175"  
  sqlpreferencesdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - SA_PASSWORD=passw0rd1234.
        - ACCEPT_EULA=Y
    ports:
        - "1433:1433"
  
  
  
  

